Created project Task7
Kyrylo11/Kh-067-QA-01-Bokhan-Kyrylo pull request #11
Opened 2022-05-08 14:34 UTC by Kyrylo11

2022-05-10 19:47 UTC, tiggggggo requested changes
имена интерфейсов должны быть с большой буквы

2022-05-10 19:48 UTC, tiggggggo requested changes
имена методов должны начинаться с маленькой буквы и должны быть действиями

2022-05-12 19:23 UTC, tiggggggo requested changes
task2 не надо менять в этом задании, верни код который был

2022-05-13 06:59 UTC, Kyrylo11 commented
Вот, вернул старую версию. Не могу понять, почему-то на таск2 залился другой проект. Видимо, где-то с файлами напутал

2022-05-15 19:52 UTC, tiggggggo approved these changes

2022-05-16 06:15 UTC, merged